# SSH Public Key must be passed in order to access the server
# There are three ways to pass the key:
# 1. PUBLIC_KEY: The key itself
# 2. PUBLIC_KEY_FILE: The path to the file containing the key
# 3. PUBLIC_KEY_URL: The URL to the file containing the key (e.g. https://github.com/username.keys)
# Only one of the three options is needed
environment:
  - PUBLIC_KEY=
  - PUBLIC_KEY_FILE=
  - PUBLIC_KEY_URL=

# Define here the volumes that you want to mount in the container in order to backup the data
# There is no need to specify the mount point, they will be automatically mounted in /home/sshuser/backup
volumes:
  #- my-volume
  #- /path/to/my/volume
